---
- name: Arch Linux vps provisioning
  hosts: all
  vars:
      USERNAME: 'samir'
      PASSWORD: 'password'
      sshd_config: /etc/ssh/sshd_config
      PUBLIC_KEY:
        - ~/.ssh/linode.pub

  tasks:
    - name: Update software
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install everything
      pacman:
        name:
          - ack
          - base-devel
          - curl
          - fd
          - fzf
          - git
          - ncdu
          - neovim
          - ranger
          - docker
          - docker-compose
          - tmux
          - ufw
          - tree
          - wget
          - go
          - zsh
          - htop
          - lsof
          - python-pip
          - zsh
        state: present

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Setup Firewall
      ufw : state=enabled policy=deny

    - name: Allow SSH traffic
      ufw: rule=allow port=22 proto=tcp

    - name: Disallow password authentication
      lineinfile: dest={{ sshd_config }}
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Disable empty password login
      lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
      notify: Restart ssh

    - name: Disable challenge response authentication
      lineinfile: dest={{ sshd_config }} regexp="^#?ChallengeResponseAuthentication" line="ChallengeResponseAuthentication no"
      notify: Restart ssh

    - name: UsePAM SSH
      lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"
      notify: Restart ssh

    - name: Enable docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Create user
      user:
        name: "{{ USERNAME }}"
        password: "{{ PASSWORD }}"
        shell: /bin/zsh
        groups: docker

    - name: Add user to sudoers
      copy:
        content: '{{ USERNAME }} ALL=(ALL) ALL'
        dest: /etc/sudoers.d/wheel_nopasswd
        mode: 0440

    - name: Add SSH key to user
      authorized_key:
        user: "{{ USERNAME }}"
        key: "{{ lookup('file', item) }}"
      with_items: "{{ PUBLIC_KEY }}"

    - name: Install dotfiles
      become: yes
      become_user: "{{ USERNAME }}"
      shell: curl -Lks bit.do/samirdotfiles | bash

    - name: Install neovim modules
      become: yes
      become_user: "{{ USERNAME }}"
      shell: pip3 install --user neovim pynvim

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh

  handlers:
  - name: Restart ssh
    service: name=sshd state=restarted
