---
- name: Arch Linux provisioning
  hosts: all
  tasks:

    - name: Upgrade
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install everything
      become: yes
      pacman:
        name:
          # Shell and console
          - ack
          - bc
          - cloc
          - ctags
          - curl
          - fd
          - fzf
          - git
          - ncdu
          - neovim
          - ranger
          - tig
          - tmux
          - tree
          - wget
          - yarn          # Needed for a neovim plugin
          - zsh

          # System tools
          - bluedevil                 # Bluetooth settings for KDE
          - cronie
          - htop
          - lsof
          - networkmanager
          - pass
          - restic
          - syncthing
          - tlp

          # Graphical tools
          - bleachbit                 # System cleaner
          - cantata                   # Music player
          - keepassxc                 # Password manager
          - pavucontrol               # Pulseaudio settings

          # Miscellaneous
          - python-pip
          - unrar                     # RAR extraction

          # Plasma
          - ki18n                     # Italian language
          - plasma-desktop            # Plasma
          - plasma-wayland-session    # KDE Wayland session
          - sddm                      # Login manager

          # KDE apps
          - ark                       # Archive manager
          - breeze-gtk                # GTK Breeze theme
          - colord-kde                # Color profiles for monitors
          - dolphin                   # File manager
          - ffmpegthumbs              # Thumbnails for dolphin
          - gwenview                  # Image viewer
          - kcalc                     # Calculator
          - kdeconnect
          - konsole                   # Terminal
          - kwalletmanager            # Wallet manager
          - okular                    # PDF reader
          - plasma-nm                 # Network manager applet
          - spectacle                 # Screenshots manager
          - sshfs                     # Used to mount device with kdeconnect

          # Settings
          - kde-gtk-config            # GTK settings
          - kscreen                   # Monitor settings
          - powerdevil                # Energy settings for KDE
          - sddm-kcm                  # Login manager settings
        state: present

    - name: Enable sddm
      become: yes
      shell: systemctl enable sddm

    - name: Install dotfiles
      shell: curl -Lks bit.do/samirdotfiles | bash

    - name: Install neovim modules
      shell: pip3 install neovim pynvim

    - name: Install additional software
      shell: pip3 install wormhole

    - name: Install yaourt
      shell: "{{ item }}"
      with_items:
        - git clone https://aur.archlinux.org/yay.git
        - cd yay
        - makepgk -si

    - name: Create user
        user:
          name: samir
          shell: /bin/zsh
          groups: wheel,users
          append: yes
