---
- name: Ubuntu provisioning
  hosts: 127.0.0.1
  tasks:

    - name: Upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install everything
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          # Shell and console
          - ack
          - bc
          - cloc
          - ctags
          - curl
          - fd
          - fzf
          - git
          - ncdu
          - neovim
          - ranger
          - tig
          - tmux
          - tree
          - wget
          - yarn          # Needed for a neovim plugin
          - zsh

          # System tools
          - bluedevil                 # Bluetooth settings for KDE
          - cronie
          - htop
          - lsof
          - networkmanager
          - pass
          - restic
          - syncthing
          - tlp
          - ufw

          # Graphical tools
          - bleachbit                 # System cleaner
          - cantata                   # Music player
          - keepassxc                 # Password manager
          - pavucontrol               # Pulseaudio settings

          # Miscellaneous
          - python-pip
          - unrar                     # RAR extraction

    - name: Install dotfiles
      shell: curl -Lks bit.do/samirdotfiles | bash

    - name: Install neovim modules
      shell: pip3 install neovim pynvim

    - name: Enable firewall
      shell: "{{ item }}"
      with_items:
         - ufw disable
         - ufw enable
         - ufw default deny incoming
         - ufw default allow outgoing
         - ufw allow 22
         - ufw allow 80

    - name: Create user
        user:
          name: samir
          shell: /bin/zsh
          groups: wheel,users
          append: yes
